spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: PROFILE-SERVICE
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/profile/**
        - id: EDUCATION-SERVICE
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path=/api/education/**
        - id: EXPERIENCE-SERVICE
          uri: lb://EXPERIENCE-SERVICE
          predicates:
            - Path=/api/experience/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/authenticate/**
server:
  port: 9191
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
