spring:
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 6000
      maximum-pool-size: 5
    password: root
    url: jdbc:mysql://localhost:3306/education
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect       
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 9000
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
customProperty:
   test: DishaS
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
api:
  customer: http://EDUCATION-SERVICE/customer  
