spring:
  datasource:
      username: newroot
      password: root
      url: jdbc:mysql://localhost:3306/profile
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
customProperty:
  test: account22
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
api:
  user: http://USER-SERVICE/api/user
